# A sample Gemfile
source 'https://rubygems.org'
ruby '1.9.3'
gem 'capybara', '2.1.0'
gem 'selenium-webdriver', '2.35.1'
gem 'cucumber', '1.3.5'
gem 'rspec'
gem 'activesupport'
gem 'i18n'
gem 'debugger'